export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{
          backgroundColor: "black",
          margin: "0px",
          padding: "0px",
        }}
      >
        {children}
      </body>
    </html>
  );
}
